// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metrics

import (
	"context"

	"github.com/nougght/monitoring-system/server/internal/model/metrics"
	"github.com/nougght/monitoring-system/shared/go/metric_kinds"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetricsRepository creates a new instance of MockMetricsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockMetricsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockMetricsRepository is an autogenerated mock type for the MetricsRepository type
type MockMetricsRepository struct {
	mock.Mock
}

type MockMetricsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsRepository) EXPECT() *MockMetricsRepository_Expecter {
	return &MockMetricsRepository_Expecter{mock: &_m.Mock}
}

// SaveRows provides a mock function for the type MockMetricsRepository
func (_mock *MockMetricsRepository) SaveRows(ctx context.Context, rows []metrics_model.MetricRow) error {
	ret := _mock.Called(ctx, rows)

	if len(ret) == 0 {
		panic("no return value specified for SaveRows")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []metrics_model.MetricRow) error); ok {
		r0 = returnFunc(ctx, rows)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetricsRepository_SaveRows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRows'
type MockMetricsRepository_SaveRows_Call struct {
	*mock.Call
}

// SaveRows is a helper method to define mock.On call
//   - ctx context.Context
//   - rows []metrics_model.MetricRow
func (_e *MockMetricsRepository_Expecter) SaveRows(ctx any, rows any) *MockMetricsRepository_SaveRows_Call {
	return &MockMetricsRepository_SaveRows_Call{Call: _e.mock.On("SaveRows", ctx, rows)}
}

func (_c *MockMetricsRepository_SaveRows_Call) Run(run func(ctx context.Context, rows []metrics_model.MetricRow)) *MockMetricsRepository_SaveRows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []metrics_model.MetricRow
		if args[1] != nil {
			arg1 = args[1].([]metrics_model.MetricRow)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricsRepository_SaveRows_Call) Return(err error) *MockMetricsRepository_SaveRows_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetricsRepository_SaveRows_Call) RunAndReturn(run func(ctx context.Context, rows []metrics_model.MetricRow) error) *MockMetricsRepository_SaveRows_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertMetricKinds provides a mock function for the type MockMetricsRepository
func (_mock *MockMetricsRepository) UpsertMetricKinds(ctx context.Context, kinds []metrickinds.MetricKindInfo) error {
	ret := _mock.Called(ctx, kinds)

	if len(ret) == 0 {
		panic("no return value specified for UpsertMetricKinds")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []metrickinds.MetricKindInfo) error); ok {
		r0 = returnFunc(ctx, kinds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetricsRepository_UpsertMetricKinds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertMetricKinds'
type MockMetricsRepository_UpsertMetricKinds_Call struct {
	*mock.Call
}

// UpsertMetricKinds is a helper method to define mock.On call
//   - ctx context.Context
//   - kinds []metrickinds.MetricKindInfo
func (_e *MockMetricsRepository_Expecter) UpsertMetricKinds(ctx any, kinds any) *MockMetricsRepository_UpsertMetricKinds_Call {
	return &MockMetricsRepository_UpsertMetricKinds_Call{Call: _e.mock.On("UpsertMetricKinds", ctx, kinds)}
}

func (_c *MockMetricsRepository_UpsertMetricKinds_Call) Run(run func(ctx context.Context, kinds []metrickinds.MetricKindInfo)) *MockMetricsRepository_UpsertMetricKinds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []metrickinds.MetricKindInfo
		if args[1] != nil {
			arg1 = args[1].([]metrickinds.MetricKindInfo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricsRepository_UpsertMetricKinds_Call) Return(err error) *MockMetricsRepository_UpsertMetricKinds_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetricsRepository_UpsertMetricKinds_Call) RunAndReturn(run func(ctx context.Context, kinds []metrickinds.MetricKindInfo) error) *MockMetricsRepository_UpsertMetricKinds_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSeriesProvider creates a new instance of MockSeriesProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSeriesProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSeriesProvider {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSeriesProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSeriesProvider is an autogenerated mock type for the SeriesProvider type
type MockSeriesProvider struct {
	mock.Mock
}

type MockSeriesProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSeriesProvider) EXPECT() *MockSeriesProvider_Expecter {
	return &MockSeriesProvider_Expecter{mock: &_m.Mock}
}

// LoadAllSeries provides a mock function for the type MockSeriesProvider
func (_mock *MockSeriesProvider) LoadAllSeries(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadAllSeries")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSeriesProvider_LoadAllSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadAllSeries'
type MockSeriesProvider_LoadAllSeries_Call struct {
	*mock.Call
}

// LoadAllSeries is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSeriesProvider_Expecter) LoadAllSeries(ctx any) *MockSeriesProvider_LoadAllSeries_Call {
	return &MockSeriesProvider_LoadAllSeries_Call{Call: _e.mock.On("LoadAllSeries", ctx)}
}

func (_c *MockSeriesProvider_LoadAllSeries_Call) Run(run func(ctx context.Context)) *MockSeriesProvider_LoadAllSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSeriesProvider_LoadAllSeries_Call) Return(err error) *MockSeriesProvider_LoadAllSeries_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSeriesProvider_LoadAllSeries_Call) RunAndReturn(run func(ctx context.Context) error) *MockSeriesProvider_LoadAllSeries_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveAllSeries provides a mock function for the type MockSeriesProvider
func (_mock *MockSeriesProvider) ResolveAllSeries(ctx context.Context, keys []metrics_model.MetricSeriesKey) (map[metrics_model.MetricSeriesKey]metrics_model.MetricSeriesID, error) {
	ret := _mock.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for ResolveAllSeries")
	}

	var r0 map[metrics_model.MetricSeriesKey]metrics_model.MetricSeriesID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []metrics_model.MetricSeriesKey) (map[metrics_model.MetricSeriesKey]metrics_model.MetricSeriesID, error)); ok {
		return returnFunc(ctx, keys)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []metrics_model.MetricSeriesKey) map[metrics_model.MetricSeriesKey]metrics_model.MetricSeriesID); ok {
		r0 = returnFunc(ctx, keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[metrics_model.MetricSeriesKey]metrics_model.MetricSeriesID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []metrics_model.MetricSeriesKey) error); ok {
		r1 = returnFunc(ctx, keys)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSeriesProvider_ResolveAllSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveAllSeries'
type MockSeriesProvider_ResolveAllSeries_Call struct {
	*mock.Call
}

// ResolveAllSeries is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []metrics_model.MetricSeriesKey
func (_e *MockSeriesProvider_Expecter) ResolveAllSeries(ctx any, keys any) *MockSeriesProvider_ResolveAllSeries_Call {
	return &MockSeriesProvider_ResolveAllSeries_Call{Call: _e.mock.On("ResolveAllSeries", ctx, keys)}
}

func (_c *MockSeriesProvider_ResolveAllSeries_Call) Run(run func(ctx context.Context, keys []metrics_model.MetricSeriesKey)) *MockSeriesProvider_ResolveAllSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []metrics_model.MetricSeriesKey
		if args[1] != nil {
			arg1 = args[1].([]metrics_model.MetricSeriesKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSeriesProvider_ResolveAllSeries_Call) Return(resultIDs map[metrics_model.MetricSeriesKey]metrics_model.MetricSeriesID, err error) *MockSeriesProvider_ResolveAllSeries_Call {
	_c.Call.Return(resultIDs, err)
	return _c
}

func (_c *MockSeriesProvider_ResolveAllSeries_Call) RunAndReturn(run func(ctx context.Context, keys []metrics_model.MetricSeriesKey) (map[metrics_model.MetricSeriesKey]metrics_model.MetricSeriesID, error)) *MockSeriesProvider_ResolveAllSeries_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSeriesRepository creates a new instance of MockSeriesRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSeriesRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSeriesRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSeriesRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSeriesRepository is an autogenerated mock type for the SeriesRepository type
type MockSeriesRepository struct {
	mock.Mock
}

type MockSeriesRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSeriesRepository) EXPECT() *MockSeriesRepository_Expecter {
	return &MockSeriesRepository_Expecter{mock: &_m.Mock}
}

// BatchCreateOrLoadSeries provides a mock function for the type MockSeriesRepository
func (_mock *MockSeriesRepository) BatchCreateOrLoadSeries(ctx context.Context, seriesList []metrics_model.MetricSeriesKey) ([]metrics_model.MetricSeries, error) {
	ret := _mock.Called(ctx, seriesList)

	if len(ret) == 0 {
		panic("no return value specified for BatchCreateOrLoadSeries")
	}

	var r0 []metrics_model.MetricSeries
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []metrics_model.MetricSeriesKey) ([]metrics_model.MetricSeries, error)); ok {
		return returnFunc(ctx, seriesList)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []metrics_model.MetricSeriesKey) []metrics_model.MetricSeries); ok {
		r0 = returnFunc(ctx, seriesList)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]metrics_model.MetricSeries)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []metrics_model.MetricSeriesKey) error); ok {
		r1 = returnFunc(ctx, seriesList)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSeriesRepository_BatchCreateOrLoadSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchCreateOrLoadSeries'
type MockSeriesRepository_BatchCreateOrLoadSeries_Call struct {
	*mock.Call
}

// BatchCreateOrLoadSeries is a helper method to define mock.On call
//   - ctx context.Context
//   - seriesList []metrics_model.MetricSeriesKey
func (_e *MockSeriesRepository_Expecter) BatchCreateOrLoadSeries(ctx any, seriesList any) *MockSeriesRepository_BatchCreateOrLoadSeries_Call {
	return &MockSeriesRepository_BatchCreateOrLoadSeries_Call{Call: _e.mock.On("BatchCreateOrLoadSeries", ctx, seriesList)}
}

func (_c *MockSeriesRepository_BatchCreateOrLoadSeries_Call) Run(run func(ctx context.Context, seriesList []metrics_model.MetricSeriesKey)) *MockSeriesRepository_BatchCreateOrLoadSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []metrics_model.MetricSeriesKey
		if args[1] != nil {
			arg1 = args[1].([]metrics_model.MetricSeriesKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSeriesRepository_BatchCreateOrLoadSeries_Call) Return(metricSeriess []metrics_model.MetricSeries, err error) *MockSeriesRepository_BatchCreateOrLoadSeries_Call {
	_c.Call.Return(metricSeriess, err)
	return _c
}

func (_c *MockSeriesRepository_BatchCreateOrLoadSeries_Call) RunAndReturn(run func(ctx context.Context, seriesList []metrics_model.MetricSeriesKey) ([]metrics_model.MetricSeries, error)) *MockSeriesRepository_BatchCreateOrLoadSeries_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllSeries provides a mock function for the type MockSeriesRepository
func (_mock *MockSeriesRepository) GetAllSeries(ctx context.Context) ([]*metrics_model.MetricSeries, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllSeries")
	}

	var r0 []*metrics_model.MetricSeries
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*metrics_model.MetricSeries, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*metrics_model.MetricSeries); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*metrics_model.MetricSeries)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSeriesRepository_GetAllSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllSeries'
type MockSeriesRepository_GetAllSeries_Call struct {
	*mock.Call
}

// GetAllSeries is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSeriesRepository_Expecter) GetAllSeries(ctx any) *MockSeriesRepository_GetAllSeries_Call {
	return &MockSeriesRepository_GetAllSeries_Call{Call: _e.mock.On("GetAllSeries", ctx)}
}

func (_c *MockSeriesRepository_GetAllSeries_Call) Run(run func(ctx context.Context)) *MockSeriesRepository_GetAllSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSeriesRepository_GetAllSeries_Call) Return(metricSeriess []*metrics_model.MetricSeries, err error) *MockSeriesRepository_GetAllSeries_Call {
	_c.Call.Return(metricSeriess, err)
	return _c
}

func (_c *MockSeriesRepository_GetAllSeries_Call) RunAndReturn(run func(ctx context.Context) ([]*metrics_model.MetricSeries, error)) *MockSeriesRepository_GetAllSeries_Call {
	_c.Call.Return(run)
	return _c
}
