/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Monitoring Server API
 * OpenAPI spec version: 1.0
 */
import type { AgentsSummary } from './agentsSummary';
import type { TopNAgents } from './topNAgents';

export interface AgentsOverview {
  summary?: AgentsSummary;
  topN?: TopNAgents;
}
