/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Monitoring Server API
 * OpenAPI spec version: 1.0
 */

export interface AgentGroup {
  createdAt?: string;
  deletedAt?: string;
  description?: string;
  id?: string;
  name?: string;
}
