/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Monitoring Server API
 * OpenAPI spec version: 1.0
 */
import type { CountDistribution } from './countDistribution';

export interface AgentsSummary {
  averageCPUUsage?: number;
  averageMemoryUsage?: number;
  cpuUsageDistribution?: CountDistribution;
  diskUsageDistribution?: CountDistribution;
  memoryUsageDistribution?: CountDistribution;
  onlineAgents?: number;
  totalAgents?: number;
}
