/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Monitoring Server API
 * OpenAPI spec version: 1.0
 */

export * from './agent';
export * from './agentConfigBody';
export * from './agentGroup';
export * from './agentsOverview';
export * from './agentSpecs';
export * from './agentsSummary';
export * from './agentWithCPUUsageDTO';
export * from './agentWithMemoryUsageDTO';
export * from './countByPercent';
export * from './countDistribution';
export * from './cpuSpecs';
export * from './createAgentBody';
export * from './createAgentGroupBody';
export * from './createAgentResponse';
export * from './diskSpecs';
export * from './errorResponse';
export * from './hostSpecs';
export * from './memorySpecs';
export * from './physicalMemoryInfo';
export * from './topNAgents';
export * from './updateAgentGroupBody';
