/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Monitoring Server API
 * OpenAPI spec version: 1.0
 */
import type { AgentWithCPUUsageDTO } from './agentWithCPUUsageDTO';
import type { AgentWithMemoryUsageDTO } from './agentWithMemoryUsageDTO';

export interface TopNAgents {
  cpuUsage?: AgentWithCPUUsageDTO[];
  memoryUsage?: AgentWithMemoryUsageDTO[];
}
