// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package agent

import (
	"context"

	"github.com/google/uuid"
	"github.com/nougght/monitoring-system/server/internal/model/agent"
	"github.com/nougght/monitoring-system/server/internal/model/metrics"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRequester creates a new instance of MockRequester. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequester(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequester {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRequester{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRequester is an autogenerated mock type for the Requester type
type MockRequester struct {
	mock.Mock
}

type MockRequester_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequester) EXPECT() *MockRequester_Expecter {
	return &MockRequester_Expecter{mock: &_m.Mock}
}

// RequestSpecifications provides a mock function for the type MockRequester
func (_mock *MockRequester) RequestSpecifications(ctx context.Context, agentID uuid.UUID) (*agent_model.Specs, error) {
	ret := _mock.Called(ctx, agentID)

	if len(ret) == 0 {
		panic("no return value specified for RequestSpecifications")
	}

	var r0 *agent_model.Specs
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*agent_model.Specs, error)); ok {
		return returnFunc(ctx, agentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *agent_model.Specs); ok {
		r0 = returnFunc(ctx, agentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agent_model.Specs)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, agentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRequester_RequestSpecifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestSpecifications'
type MockRequester_RequestSpecifications_Call struct {
	*mock.Call
}

// RequestSpecifications is a helper method to define mock.On call
//   - ctx context.Context
//   - agentID uuid.UUID
func (_e *MockRequester_Expecter) RequestSpecifications(ctx any, agentID any) *MockRequester_RequestSpecifications_Call {
	return &MockRequester_RequestSpecifications_Call{Call: _e.mock.On("RequestSpecifications", ctx, agentID)}
}

func (_c *MockRequester_RequestSpecifications_Call) Run(run func(ctx context.Context, agentID uuid.UUID)) *MockRequester_RequestSpecifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRequester_RequestSpecifications_Call) Return(specs *agent_model.Specs, err error) *MockRequester_RequestSpecifications_Call {
	_c.Call.Return(specs, err)
	return _c
}

func (_c *MockRequester_RequestSpecifications_Call) RunAndReturn(run func(ctx context.Context, agentID uuid.UUID) (*agent_model.Specs, error)) *MockRequester_RequestSpecifications_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMetricsService creates a new instance of MockMetricsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockMetricsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockMetricsService is an autogenerated mock type for the MetricsService type
type MockMetricsService struct {
	mock.Mock
}

type MockMetricsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsService) EXPECT() *MockMetricsService_Expecter {
	return &MockMetricsService_Expecter{mock: &_m.Mock}
}

// HandleActivityUpdate provides a mock function for the type MockMetricsService
func (_mock *MockMetricsService) HandleActivityUpdate(ctx context.Context, update *metrics_model.ActivityUpdate) error {
	ret := _mock.Called(ctx, update)

	if len(ret) == 0 {
		panic("no return value specified for HandleActivityUpdate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *metrics_model.ActivityUpdate) error); ok {
		r0 = returnFunc(ctx, update)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetricsService_HandleActivityUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleActivityUpdate'
type MockMetricsService_HandleActivityUpdate_Call struct {
	*mock.Call
}

// HandleActivityUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - update *metrics_model.ActivityUpdate
func (_e *MockMetricsService_Expecter) HandleActivityUpdate(ctx any, update any) *MockMetricsService_HandleActivityUpdate_Call {
	return &MockMetricsService_HandleActivityUpdate_Call{Call: _e.mock.On("HandleActivityUpdate", ctx, update)}
}

func (_c *MockMetricsService_HandleActivityUpdate_Call) Run(run func(ctx context.Context, update *metrics_model.ActivityUpdate)) *MockMetricsService_HandleActivityUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *metrics_model.ActivityUpdate
		if args[1] != nil {
			arg1 = args[1].(*metrics_model.ActivityUpdate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricsService_HandleActivityUpdate_Call) Return(err error) *MockMetricsService_HandleActivityUpdate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetricsService_HandleActivityUpdate_Call) RunAndReturn(run func(ctx context.Context, update *metrics_model.ActivityUpdate) error) *MockMetricsService_HandleActivityUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// HandleMetrics provides a mock function for the type MockMetricsService
func (_mock *MockMetricsService) HandleMetrics(ctx context.Context, agentID uuid.UUID, metrics metrics_model.MetricsBatch) error {
	ret := _mock.Called(ctx, agentID, metrics)

	if len(ret) == 0 {
		panic("no return value specified for HandleMetrics")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, metrics_model.MetricsBatch) error); ok {
		r0 = returnFunc(ctx, agentID, metrics)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetricsService_HandleMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleMetrics'
type MockMetricsService_HandleMetrics_Call struct {
	*mock.Call
}

// HandleMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - agentID uuid.UUID
//   - metrics metrics_model.MetricsBatch
func (_e *MockMetricsService_Expecter) HandleMetrics(ctx any, agentID any, metrics any) *MockMetricsService_HandleMetrics_Call {
	return &MockMetricsService_HandleMetrics_Call{Call: _e.mock.On("HandleMetrics", ctx, agentID, metrics)}
}

func (_c *MockMetricsService_HandleMetrics_Call) Run(run func(ctx context.Context, agentID uuid.UUID, metrics metrics_model.MetricsBatch)) *MockMetricsService_HandleMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 metrics_model.MetricsBatch
		if args[2] != nil {
			arg2 = args[2].(metrics_model.MetricsBatch)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetricsService_HandleMetrics_Call) Return(err error) *MockMetricsService_HandleMetrics_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetricsService_HandleMetrics_Call) RunAndReturn(run func(ctx context.Context, agentID uuid.UUID, metrics metrics_model.MetricsBatch) error) *MockMetricsService_HandleMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAgentRegistryService creates a new instance of MockAgentRegistryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentRegistryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentRegistryService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAgentRegistryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAgentRegistryService is an autogenerated mock type for the AgentRegistryService type
type MockAgentRegistryService struct {
	mock.Mock
}

type MockAgentRegistryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentRegistryService) EXPECT() *MockAgentRegistryService_Expecter {
	return &MockAgentRegistryService_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type MockAgentRegistryService
func (_mock *MockAgentRegistryService) CreateSession(agentID uuid.UUID) *agent_model.AgentSession {
	ret := _mock.Called(agentID)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *agent_model.AgentSession
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *agent_model.AgentSession); ok {
		r0 = returnFunc(agentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agent_model.AgentSession)
		}
	}
	return r0
}

// MockAgentRegistryService_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockAgentRegistryService_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - agentID uuid.UUID
func (_e *MockAgentRegistryService_Expecter) CreateSession(agentID any) *MockAgentRegistryService_CreateSession_Call {
	return &MockAgentRegistryService_CreateSession_Call{Call: _e.mock.On("CreateSession", agentID)}
}

func (_c *MockAgentRegistryService_CreateSession_Call) Run(run func(agentID uuid.UUID)) *MockAgentRegistryService_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgentRegistryService_CreateSession_Call) Return(agentSession *agent_model.AgentSession) *MockAgentRegistryService_CreateSession_Call {
	_c.Call.Return(agentSession)
	return _c
}

func (_c *MockAgentRegistryService_CreateSession_Call) RunAndReturn(run func(agentID uuid.UUID) *agent_model.AgentSession) *MockAgentRegistryService_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// Enroll provides a mock function for the type MockAgentRegistryService
func (_mock *MockAgentRegistryService) Enroll(ctx context.Context, params *agent_model.EnrollParams) (*agent_model.EnrollResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Enroll")
	}

	var r0 *agent_model.EnrollResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *agent_model.EnrollParams) (*agent_model.EnrollResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *agent_model.EnrollParams) *agent_model.EnrollResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agent_model.EnrollResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *agent_model.EnrollParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentRegistryService_Enroll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enroll'
type MockAgentRegistryService_Enroll_Call struct {
	*mock.Call
}

// Enroll is a helper method to define mock.On call
//   - ctx context.Context
//   - params *agent_model.EnrollParams
func (_e *MockAgentRegistryService_Expecter) Enroll(ctx any, params any) *MockAgentRegistryService_Enroll_Call {
	return &MockAgentRegistryService_Enroll_Call{Call: _e.mock.On("Enroll", ctx, params)}
}

func (_c *MockAgentRegistryService_Enroll_Call) Run(run func(ctx context.Context, params *agent_model.EnrollParams)) *MockAgentRegistryService_Enroll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *agent_model.EnrollParams
		if args[1] != nil {
			arg1 = args[1].(*agent_model.EnrollParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgentRegistryService_Enroll_Call) Return(enrollResult *agent_model.EnrollResult, err error) *MockAgentRegistryService_Enroll_Call {
	_c.Call.Return(enrollResult, err)
	return _c
}

func (_c *MockAgentRegistryService_Enroll_Call) RunAndReturn(run func(ctx context.Context, params *agent_model.EnrollParams) (*agent_model.EnrollResult, error)) *MockAgentRegistryService_Enroll_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function for the type MockAgentRegistryService
func (_mock *MockAgentRegistryService) GetSession(agentID uuid.UUID) (*agent_model.AgentSession, bool) {
	ret := _mock.Called(agentID)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *agent_model.AgentSession
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*agent_model.AgentSession, bool)); ok {
		return returnFunc(agentID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *agent_model.AgentSession); ok {
		r0 = returnFunc(agentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agent_model.AgentSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) bool); ok {
		r1 = returnFunc(agentID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockAgentRegistryService_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockAgentRegistryService_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - agentID uuid.UUID
func (_e *MockAgentRegistryService_Expecter) GetSession(agentID any) *MockAgentRegistryService_GetSession_Call {
	return &MockAgentRegistryService_GetSession_Call{Call: _e.mock.On("GetSession", agentID)}
}

func (_c *MockAgentRegistryService_GetSession_Call) Run(run func(agentID uuid.UUID)) *MockAgentRegistryService_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgentRegistryService_GetSession_Call) Return(agentSession *agent_model.AgentSession, b bool) *MockAgentRegistryService_GetSession_Call {
	_c.Call.Return(agentSession, b)
	return _c
}

func (_c *MockAgentRegistryService_GetSession_Call) RunAndReturn(run func(agentID uuid.UUID) (*agent_model.AgentSession, bool)) *MockAgentRegistryService_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveSession provides a mock function for the type MockAgentRegistryService
func (_mock *MockAgentRegistryService) RemoveSession(agentID uuid.UUID) {
	_mock.Called(agentID)
	return
}

// MockAgentRegistryService_RemoveSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveSession'
type MockAgentRegistryService_RemoveSession_Call struct {
	*mock.Call
}

// RemoveSession is a helper method to define mock.On call
//   - agentID uuid.UUID
func (_e *MockAgentRegistryService_Expecter) RemoveSession(agentID any) *MockAgentRegistryService_RemoveSession_Call {
	return &MockAgentRegistryService_RemoveSession_Call{Call: _e.mock.On("RemoveSession", agentID)}
}

func (_c *MockAgentRegistryService_RemoveSession_Call) Run(run func(agentID uuid.UUID)) *MockAgentRegistryService_RemoveSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgentRegistryService_RemoveSession_Call) Return() *MockAgentRegistryService_RemoveSession_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAgentRegistryService_RemoveSession_Call) RunAndReturn(run func(agentID uuid.UUID)) *MockAgentRegistryService_RemoveSession_Call {
	_c.Run(run)
	return _c
}

// UpdateSpecifications provides a mock function for the type MockAgentRegistryService
func (_mock *MockAgentRegistryService) UpdateSpecifications(ctx context.Context, agentID uuid.UUID, specifications *agent_model.Specs) error {
	ret := _mock.Called(ctx, agentID, specifications)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSpecifications")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *agent_model.Specs) error); ok {
		r0 = returnFunc(ctx, agentID, specifications)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgentRegistryService_UpdateSpecifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSpecifications'
type MockAgentRegistryService_UpdateSpecifications_Call struct {
	*mock.Call
}

// UpdateSpecifications is a helper method to define mock.On call
//   - ctx context.Context
//   - agentID uuid.UUID
//   - specifications *agent_model.Specs
func (_e *MockAgentRegistryService_Expecter) UpdateSpecifications(ctx any, agentID any, specifications any) *MockAgentRegistryService_UpdateSpecifications_Call {
	return &MockAgentRegistryService_UpdateSpecifications_Call{Call: _e.mock.On("UpdateSpecifications", ctx, agentID, specifications)}
}

func (_c *MockAgentRegistryService_UpdateSpecifications_Call) Run(run func(ctx context.Context, agentID uuid.UUID, specifications *agent_model.Specs)) *MockAgentRegistryService_UpdateSpecifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *agent_model.Specs
		if args[2] != nil {
			arg2 = args[2].(*agent_model.Specs)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAgentRegistryService_UpdateSpecifications_Call) Return(err error) *MockAgentRegistryService_UpdateSpecifications_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgentRegistryService_UpdateSpecifications_Call) RunAndReturn(run func(ctx context.Context, agentID uuid.UUID, specifications *agent_model.Specs) error) *MockAgentRegistryService_UpdateSpecifications_Call {
	_c.Call.Return(run)
	return _c
}
