// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package realtime

import (
	"context"

	"github.com/nougght/monitoring-system/server/internal/model/overview"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOverviewService creates a new instance of MockOverviewService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOverviewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOverviewService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockOverviewService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockOverviewService is an autogenerated mock type for the OverviewService type
type MockOverviewService struct {
	mock.Mock
}

type MockOverviewService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOverviewService) EXPECT() *MockOverviewService_Expecter {
	return &MockOverviewService_Expecter{mock: &_m.Mock}
}

// GetOverview provides a mock function for the type MockOverviewService
func (_mock *MockOverviewService) GetOverview(ctx context.Context) (*overview_model.AgentsOverview, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOverview")
	}

	var r0 *overview_model.AgentsOverview
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*overview_model.AgentsOverview, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *overview_model.AgentsOverview); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*overview_model.AgentsOverview)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOverviewService_GetOverview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOverview'
type MockOverviewService_GetOverview_Call struct {
	*mock.Call
}

// GetOverview is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOverviewService_Expecter) GetOverview(ctx any) *MockOverviewService_GetOverview_Call {
	return &MockOverviewService_GetOverview_Call{Call: _e.mock.On("GetOverview", ctx)}
}

func (_c *MockOverviewService_GetOverview_Call) Run(run func(ctx context.Context)) *MockOverviewService_GetOverview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOverviewService_GetOverview_Call) Return(agentsOverview *overview_model.AgentsOverview, err error) *MockOverviewService_GetOverview_Call {
	_c.Call.Return(agentsOverview, err)
	return _c
}

func (_c *MockOverviewService_GetOverview_Call) RunAndReturn(run func(ctx context.Context) (*overview_model.AgentsOverview, error)) *MockOverviewService_GetOverview_Call {
	_c.Call.Return(run)
	return _c
}
