// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package overview

import (
	"context"

	"github.com/google/uuid"
	"github.com/nougght/monitoring-system/server/internal/model/agent"
	"github.com/nougght/monitoring-system/server/internal/model/metrics"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetricsService creates a new instance of MockMetricsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockMetricsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockMetricsService is an autogenerated mock type for the MetricsService type
type MockMetricsService struct {
	mock.Mock
}

type MockMetricsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsService) EXPECT() *MockMetricsService_Expecter {
	return &MockMetricsService_Expecter{mock: &_m.Mock}
}

// GetSnapshots provides a mock function for the type MockMetricsService
func (_mock *MockMetricsService) GetSnapshots() map[uuid.UUID]*metrics_model.Snapshot {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSnapshots")
	}

	var r0 map[uuid.UUID]*metrics_model.Snapshot
	if returnFunc, ok := ret.Get(0).(func() map[uuid.UUID]*metrics_model.Snapshot); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID]*metrics_model.Snapshot)
		}
	}
	return r0
}

// MockMetricsService_GetSnapshots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSnapshots'
type MockMetricsService_GetSnapshots_Call struct {
	*mock.Call
}

// GetSnapshots is a helper method to define mock.On call
func (_e *MockMetricsService_Expecter) GetSnapshots() *MockMetricsService_GetSnapshots_Call {
	return &MockMetricsService_GetSnapshots_Call{Call: _e.mock.On("GetSnapshots")}
}

func (_c *MockMetricsService_GetSnapshots_Call) Run(run func()) *MockMetricsService_GetSnapshots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetricsService_GetSnapshots_Call) Return(uUIDToSnapshot map[uuid.UUID]*metrics_model.Snapshot) *MockMetricsService_GetSnapshots_Call {
	_c.Call.Return(uUIDToSnapshot)
	return _c
}

func (_c *MockMetricsService_GetSnapshots_Call) RunAndReturn(run func() map[uuid.UUID]*metrics_model.Snapshot) *MockMetricsService_GetSnapshots_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAgentRegistryService creates a new instance of MockAgentRegistryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentRegistryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentRegistryService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAgentRegistryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAgentRegistryService is an autogenerated mock type for the AgentRegistryService type
type MockAgentRegistryService struct {
	mock.Mock
}

type MockAgentRegistryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentRegistryService) EXPECT() *MockAgentRegistryService_Expecter {
	return &MockAgentRegistryService_Expecter{mock: &_m.Mock}
}

// GetAgentNamesByIDs provides a mock function for the type MockAgentRegistryService
func (_mock *MockAgentRegistryService) GetAgentNamesByIDs(ctx context.Context, agentIDs []uuid.UUID) (map[uuid.UUID]string, error) {
	ret := _mock.Called(ctx, agentIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetAgentNamesByIDs")
	}

	var r0 map[uuid.UUID]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) (map[uuid.UUID]string, error)); ok {
		return returnFunc(ctx, agentIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) map[uuid.UUID]string); ok {
		r0 = returnFunc(ctx, agentIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, agentIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentRegistryService_GetAgentNamesByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAgentNamesByIDs'
type MockAgentRegistryService_GetAgentNamesByIDs_Call struct {
	*mock.Call
}

// GetAgentNamesByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - agentIDs []uuid.UUID
func (_e *MockAgentRegistryService_Expecter) GetAgentNamesByIDs(ctx any, agentIDs any) *MockAgentRegistryService_GetAgentNamesByIDs_Call {
	return &MockAgentRegistryService_GetAgentNamesByIDs_Call{Call: _e.mock.On("GetAgentNamesByIDs", ctx, agentIDs)}
}

func (_c *MockAgentRegistryService_GetAgentNamesByIDs_Call) Run(run func(ctx context.Context, agentIDs []uuid.UUID)) *MockAgentRegistryService_GetAgentNamesByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgentRegistryService_GetAgentNamesByIDs_Call) Return(uUIDToString map[uuid.UUID]string, err error) *MockAgentRegistryService_GetAgentNamesByIDs_Call {
	_c.Call.Return(uUIDToString, err)
	return _c
}

func (_c *MockAgentRegistryService_GetAgentNamesByIDs_Call) RunAndReturn(run func(ctx context.Context, agentIDs []uuid.UUID) (map[uuid.UUID]string, error)) *MockAgentRegistryService_GetAgentNamesByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetSpecsTotalList provides a mock function for the type MockAgentRegistryService
func (_mock *MockAgentRegistryService) GetSpecsTotalList(ctx context.Context, agentIDs []uuid.UUID) (map[uuid.UUID]agent_model.SpecsTotal, error) {
	ret := _mock.Called(ctx, agentIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetSpecsTotalList")
	}

	var r0 map[uuid.UUID]agent_model.SpecsTotal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) (map[uuid.UUID]agent_model.SpecsTotal, error)); ok {
		return returnFunc(ctx, agentIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) map[uuid.UUID]agent_model.SpecsTotal); ok {
		r0 = returnFunc(ctx, agentIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID]agent_model.SpecsTotal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, agentIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentRegistryService_GetSpecsTotalList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSpecsTotalList'
type MockAgentRegistryService_GetSpecsTotalList_Call struct {
	*mock.Call
}

// GetSpecsTotalList is a helper method to define mock.On call
//   - ctx context.Context
//   - agentIDs []uuid.UUID
func (_e *MockAgentRegistryService_Expecter) GetSpecsTotalList(ctx any, agentIDs any) *MockAgentRegistryService_GetSpecsTotalList_Call {
	return &MockAgentRegistryService_GetSpecsTotalList_Call{Call: _e.mock.On("GetSpecsTotalList", ctx, agentIDs)}
}

func (_c *MockAgentRegistryService_GetSpecsTotalList_Call) Run(run func(ctx context.Context, agentIDs []uuid.UUID)) *MockAgentRegistryService_GetSpecsTotalList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgentRegistryService_GetSpecsTotalList_Call) Return(uUIDToSpecsTotal map[uuid.UUID]agent_model.SpecsTotal, err error) *MockAgentRegistryService_GetSpecsTotalList_Call {
	_c.Call.Return(uUIDToSpecsTotal, err)
	return _c
}

func (_c *MockAgentRegistryService_GetSpecsTotalList_Call) RunAndReturn(run func(ctx context.Context, agentIDs []uuid.UUID) (map[uuid.UUID]agent_model.SpecsTotal, error)) *MockAgentRegistryService_GetSpecsTotalList_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalAgents provides a mock function for the type MockAgentRegistryService
func (_mock *MockAgentRegistryService) GetTotalAgents(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalAgents")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentRegistryService_GetTotalAgents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalAgents'
type MockAgentRegistryService_GetTotalAgents_Call struct {
	*mock.Call
}

// GetTotalAgents is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAgentRegistryService_Expecter) GetTotalAgents(ctx any) *MockAgentRegistryService_GetTotalAgents_Call {
	return &MockAgentRegistryService_GetTotalAgents_Call{Call: _e.mock.On("GetTotalAgents", ctx)}
}

func (_c *MockAgentRegistryService_GetTotalAgents_Call) Run(run func(ctx context.Context)) *MockAgentRegistryService_GetTotalAgents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgentRegistryService_GetTotalAgents_Call) Return(n int, err error) *MockAgentRegistryService_GetTotalAgents_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAgentRegistryService_GetTotalAgents_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockAgentRegistryService_GetTotalAgents_Call {
	_c.Call.Return(run)
	return _c
}

// IsOnline provides a mock function for the type MockAgentRegistryService
func (_mock *MockAgentRegistryService) IsOnline(agentID uuid.UUID) bool {
	ret := _mock.Called(agentID)

	if len(ret) == 0 {
		panic("no return value specified for IsOnline")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) bool); ok {
		r0 = returnFunc(agentID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockAgentRegistryService_IsOnline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOnline'
type MockAgentRegistryService_IsOnline_Call struct {
	*mock.Call
}

// IsOnline is a helper method to define mock.On call
//   - agentID uuid.UUID
func (_e *MockAgentRegistryService_Expecter) IsOnline(agentID any) *MockAgentRegistryService_IsOnline_Call {
	return &MockAgentRegistryService_IsOnline_Call{Call: _e.mock.On("IsOnline", agentID)}
}

func (_c *MockAgentRegistryService_IsOnline_Call) Run(run func(agentID uuid.UUID)) *MockAgentRegistryService_IsOnline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgentRegistryService_IsOnline_Call) Return(b bool) *MockAgentRegistryService_IsOnline_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockAgentRegistryService_IsOnline_Call) RunAndReturn(run func(agentID uuid.UUID) bool) *MockAgentRegistryService_IsOnline_Call {
	_c.Call.Return(run)
	return _c
}
