// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rest

import (
	"context"

	"github.com/google/uuid"
	"github.com/nougght/monitoring-system/server/internal/model/agent"
	"github.com/nougght/monitoring-system/server/internal/model/overview"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAgentRegistryService creates a new instance of MockAgentRegistryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentRegistryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentRegistryService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAgentRegistryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAgentRegistryService is an autogenerated mock type for the AgentRegistryService type
type MockAgentRegistryService struct {
	mock.Mock
}

type MockAgentRegistryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentRegistryService) EXPECT() *MockAgentRegistryService_Expecter {
	return &MockAgentRegistryService_Expecter{mock: &_m.Mock}
}

// CreateAgent provides a mock function for the type MockAgentRegistryService
func (_mock *MockAgentRegistryService) CreateAgent(ctx context.Context, name string, description *string) (*agent_model.CreateAgentResult, error) {
	ret := _mock.Called(ctx, name, description)

	if len(ret) == 0 {
		panic("no return value specified for CreateAgent")
	}

	var r0 *agent_model.CreateAgentResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string) (*agent_model.CreateAgentResult, error)); ok {
		return returnFunc(ctx, name, description)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *string) *agent_model.CreateAgentResult); ok {
		r0 = returnFunc(ctx, name, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agent_model.CreateAgentResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *string) error); ok {
		r1 = returnFunc(ctx, name, description)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentRegistryService_CreateAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAgent'
type MockAgentRegistryService_CreateAgent_Call struct {
	*mock.Call
}

// CreateAgent is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - description *string
func (_e *MockAgentRegistryService_Expecter) CreateAgent(ctx any, name any, description any) *MockAgentRegistryService_CreateAgent_Call {
	return &MockAgentRegistryService_CreateAgent_Call{Call: _e.mock.On("CreateAgent", ctx, name, description)}
}

func (_c *MockAgentRegistryService_CreateAgent_Call) Run(run func(ctx context.Context, name string, description *string)) *MockAgentRegistryService_CreateAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAgentRegistryService_CreateAgent_Call) Return(createAgentResult *agent_model.CreateAgentResult, err error) *MockAgentRegistryService_CreateAgent_Call {
	_c.Call.Return(createAgentResult, err)
	return _c
}

func (_c *MockAgentRegistryService_CreateAgent_Call) RunAndReturn(run func(ctx context.Context, name string, description *string) (*agent_model.CreateAgentResult, error)) *MockAgentRegistryService_CreateAgent_Call {
	_c.Call.Return(run)
	return _c
}

// GetAgentByID provides a mock function for the type MockAgentRegistryService
func (_mock *MockAgentRegistryService) GetAgentByID(ctx context.Context, id uuid.UUID) (*agent_model.Agent, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAgentByID")
	}

	var r0 *agent_model.Agent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*agent_model.Agent, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *agent_model.Agent); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agent_model.Agent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentRegistryService_GetAgentByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAgentByID'
type MockAgentRegistryService_GetAgentByID_Call struct {
	*mock.Call
}

// GetAgentByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAgentRegistryService_Expecter) GetAgentByID(ctx any, id any) *MockAgentRegistryService_GetAgentByID_Call {
	return &MockAgentRegistryService_GetAgentByID_Call{Call: _e.mock.On("GetAgentByID", ctx, id)}
}

func (_c *MockAgentRegistryService_GetAgentByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAgentRegistryService_GetAgentByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgentRegistryService_GetAgentByID_Call) Return(agent *agent_model.Agent, err error) *MockAgentRegistryService_GetAgentByID_Call {
	_c.Call.Return(agent, err)
	return _c
}

func (_c *MockAgentRegistryService_GetAgentByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*agent_model.Agent, error)) *MockAgentRegistryService_GetAgentByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllAgents provides a mock function for the type MockAgentRegistryService
func (_mock *MockAgentRegistryService) GetAllAgents(ctx context.Context) ([]*agent_model.Agent, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAgents")
	}

	var r0 []*agent_model.Agent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*agent_model.Agent, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*agent_model.Agent); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*agent_model.Agent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentRegistryService_GetAllAgents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllAgents'
type MockAgentRegistryService_GetAllAgents_Call struct {
	*mock.Call
}

// GetAllAgents is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAgentRegistryService_Expecter) GetAllAgents(ctx any) *MockAgentRegistryService_GetAllAgents_Call {
	return &MockAgentRegistryService_GetAllAgents_Call{Call: _e.mock.On("GetAllAgents", ctx)}
}

func (_c *MockAgentRegistryService_GetAllAgents_Call) Run(run func(ctx context.Context)) *MockAgentRegistryService_GetAllAgents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgentRegistryService_GetAllAgents_Call) Return(agents []*agent_model.Agent, err error) *MockAgentRegistryService_GetAllAgents_Call {
	_c.Call.Return(agents, err)
	return _c
}

func (_c *MockAgentRegistryService_GetAllAgents_Call) RunAndReturn(run func(ctx context.Context) ([]*agent_model.Agent, error)) *MockAgentRegistryService_GetAllAgents_Call {
	_c.Call.Return(run)
	return _c
}

// GetNewAgentFiles provides a mock function for the type MockAgentRegistryService
func (_mock *MockAgentRegistryService) GetNewAgentFiles(ctx context.Context, agentID uuid.UUID, enrollmentKey string) ([]byte, error) {
	ret := _mock.Called(ctx, agentID, enrollmentKey)

	if len(ret) == 0 {
		panic("no return value specified for GetNewAgentFiles")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]byte, error)); ok {
		return returnFunc(ctx, agentID, enrollmentKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []byte); ok {
		r0 = returnFunc(ctx, agentID, enrollmentKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, agentID, enrollmentKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentRegistryService_GetNewAgentFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNewAgentFiles'
type MockAgentRegistryService_GetNewAgentFiles_Call struct {
	*mock.Call
}

// GetNewAgentFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - agentID uuid.UUID
//   - enrollmentKey string
func (_e *MockAgentRegistryService_Expecter) GetNewAgentFiles(ctx any, agentID any, enrollmentKey any) *MockAgentRegistryService_GetNewAgentFiles_Call {
	return &MockAgentRegistryService_GetNewAgentFiles_Call{Call: _e.mock.On("GetNewAgentFiles", ctx, agentID, enrollmentKey)}
}

func (_c *MockAgentRegistryService_GetNewAgentFiles_Call) Run(run func(ctx context.Context, agentID uuid.UUID, enrollmentKey string)) *MockAgentRegistryService_GetNewAgentFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAgentRegistryService_GetNewAgentFiles_Call) Return(bytes []byte, err error) *MockAgentRegistryService_GetNewAgentFiles_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockAgentRegistryService_GetNewAgentFiles_Call) RunAndReturn(run func(ctx context.Context, agentID uuid.UUID, enrollmentKey string) ([]byte, error)) *MockAgentRegistryService_GetNewAgentFiles_Call {
	_c.Call.Return(run)
	return _c
}

// GetSpecifications provides a mock function for the type MockAgentRegistryService
func (_mock *MockAgentRegistryService) GetSpecifications(ctx context.Context, agentID uuid.UUID) (*agent_model.Specs, error) {
	ret := _mock.Called(ctx, agentID)

	if len(ret) == 0 {
		panic("no return value specified for GetSpecifications")
	}

	var r0 *agent_model.Specs
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*agent_model.Specs, error)); ok {
		return returnFunc(ctx, agentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *agent_model.Specs); ok {
		r0 = returnFunc(ctx, agentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agent_model.Specs)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, agentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentRegistryService_GetSpecifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSpecifications'
type MockAgentRegistryService_GetSpecifications_Call struct {
	*mock.Call
}

// GetSpecifications is a helper method to define mock.On call
//   - ctx context.Context
//   - agentID uuid.UUID
func (_e *MockAgentRegistryService_Expecter) GetSpecifications(ctx any, agentID any) *MockAgentRegistryService_GetSpecifications_Call {
	return &MockAgentRegistryService_GetSpecifications_Call{Call: _e.mock.On("GetSpecifications", ctx, agentID)}
}

func (_c *MockAgentRegistryService_GetSpecifications_Call) Run(run func(ctx context.Context, agentID uuid.UUID)) *MockAgentRegistryService_GetSpecifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgentRegistryService_GetSpecifications_Call) Return(specs *agent_model.Specs, err error) *MockAgentRegistryService_GetSpecifications_Call {
	_c.Call.Return(specs, err)
	return _c
}

func (_c *MockAgentRegistryService_GetSpecifications_Call) RunAndReturn(run func(ctx context.Context, agentID uuid.UUID) (*agent_model.Specs, error)) *MockAgentRegistryService_GetSpecifications_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAgentInteractionService creates a new instance of MockAgentInteractionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentInteractionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentInteractionService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAgentInteractionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAgentInteractionService is an autogenerated mock type for the AgentInteractionService type
type MockAgentInteractionService struct {
	mock.Mock
}

type MockAgentInteractionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentInteractionService) EXPECT() *MockAgentInteractionService_Expecter {
	return &MockAgentInteractionService_Expecter{mock: &_m.Mock}
}

// SubStreaming provides a mock function for the type MockAgentInteractionService
func (_mock *MockAgentInteractionService) SubStreaming(agentID uuid.UUID, viewerID uuid.UUID) (<-chan []byte, error) {
	ret := _mock.Called(agentID, viewerID)

	if len(ret) == 0 {
		panic("no return value specified for SubStreaming")
	}

	var r0 <-chan []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) (<-chan []byte, error)); ok {
		return returnFunc(agentID, viewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) <-chan []byte); ok {
		r0 = returnFunc(agentID, viewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan []byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(agentID, viewerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentInteractionService_SubStreaming_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubStreaming'
type MockAgentInteractionService_SubStreaming_Call struct {
	*mock.Call
}

// SubStreaming is a helper method to define mock.On call
//   - agentID uuid.UUID
//   - viewerID uuid.UUID
func (_e *MockAgentInteractionService_Expecter) SubStreaming(agentID any, viewerID any) *MockAgentInteractionService_SubStreaming_Call {
	return &MockAgentInteractionService_SubStreaming_Call{Call: _e.mock.On("SubStreaming", agentID, viewerID)}
}

func (_c *MockAgentInteractionService_SubStreaming_Call) Run(run func(agentID uuid.UUID, viewerID uuid.UUID)) *MockAgentInteractionService_SubStreaming_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgentInteractionService_SubStreaming_Call) Return(bytesCh <-chan []byte, err error) *MockAgentInteractionService_SubStreaming_Call {
	_c.Call.Return(bytesCh, err)
	return _c
}

func (_c *MockAgentInteractionService_SubStreaming_Call) RunAndReturn(run func(agentID uuid.UUID, viewerID uuid.UUID) (<-chan []byte, error)) *MockAgentInteractionService_SubStreaming_Call {
	_c.Call.Return(run)
	return _c
}

// UnsubAllStreaming provides a mock function for the type MockAgentInteractionService
func (_mock *MockAgentInteractionService) UnsubAllStreaming(viewerID uuid.UUID) {
	_mock.Called(viewerID)
	return
}

// MockAgentInteractionService_UnsubAllStreaming_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnsubAllStreaming'
type MockAgentInteractionService_UnsubAllStreaming_Call struct {
	*mock.Call
}

// UnsubAllStreaming is a helper method to define mock.On call
//   - viewerID uuid.UUID
func (_e *MockAgentInteractionService_Expecter) UnsubAllStreaming(viewerID any) *MockAgentInteractionService_UnsubAllStreaming_Call {
	return &MockAgentInteractionService_UnsubAllStreaming_Call{Call: _e.mock.On("UnsubAllStreaming", viewerID)}
}

func (_c *MockAgentInteractionService_UnsubAllStreaming_Call) Run(run func(viewerID uuid.UUID)) *MockAgentInteractionService_UnsubAllStreaming_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgentInteractionService_UnsubAllStreaming_Call) Return() *MockAgentInteractionService_UnsubAllStreaming_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAgentInteractionService_UnsubAllStreaming_Call) RunAndReturn(run func(viewerID uuid.UUID)) *MockAgentInteractionService_UnsubAllStreaming_Call {
	_c.Run(run)
	return _c
}

// NewMockOverviewService creates a new instance of MockOverviewService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOverviewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOverviewService {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockOverviewService{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockOverviewService is an autogenerated mock type for the OverviewService type
type MockOverviewService struct {
	mock.Mock
}

type MockOverviewService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOverviewService) EXPECT() *MockOverviewService_Expecter {
	return &MockOverviewService_Expecter{mock: &_m.Mock}
}

// GetOverview provides a mock function for the type MockOverviewService
func (_mock *MockOverviewService) GetOverview(ctx context.Context) (*overview_model.AgentsOverview, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOverview")
	}

	var r0 *overview_model.AgentsOverview
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*overview_model.AgentsOverview, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *overview_model.AgentsOverview); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*overview_model.AgentsOverview)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOverviewService_GetOverview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOverview'
type MockOverviewService_GetOverview_Call struct {
	*mock.Call
}

// GetOverview is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockOverviewService_Expecter) GetOverview(ctx any) *MockOverviewService_GetOverview_Call {
	return &MockOverviewService_GetOverview_Call{Call: _e.mock.On("GetOverview", ctx)}
}

func (_c *MockOverviewService_GetOverview_Call) Run(run func(ctx context.Context)) *MockOverviewService_GetOverview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOverviewService_GetOverview_Call) Return(agentsOverview *overview_model.AgentsOverview, err error) *MockOverviewService_GetOverview_Call {
	_c.Call.Return(agentsOverview, err)
	return _c
}

func (_c *MockOverviewService_GetOverview_Call) RunAndReturn(run func(ctx context.Context) (*overview_model.AgentsOverview, error)) *MockOverviewService_GetOverview_Call {
	_c.Call.Return(run)
	return _c
}
