// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package agentregistry

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/nougght/monitoring-system/server/internal/model/agent"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAgentRepository creates a new instance of MockAgentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAgentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAgentRepository is an autogenerated mock type for the AgentRepository type
type MockAgentRepository struct {
	mock.Mock
}

type MockAgentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentRepository) EXPECT() *MockAgentRepository_Expecter {
	return &MockAgentRepository_Expecter{mock: &_m.Mock}
}

// CreateAgent provides a mock function for the type MockAgentRepository
func (_mock *MockAgentRepository) CreateAgent(ctx context.Context, agent *agent_model.Agent) (*agent_model.Agent, error) {
	ret := _mock.Called(ctx, agent)

	if len(ret) == 0 {
		panic("no return value specified for CreateAgent")
	}

	var r0 *agent_model.Agent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *agent_model.Agent) (*agent_model.Agent, error)); ok {
		return returnFunc(ctx, agent)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *agent_model.Agent) *agent_model.Agent); ok {
		r0 = returnFunc(ctx, agent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agent_model.Agent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *agent_model.Agent) error); ok {
		r1 = returnFunc(ctx, agent)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentRepository_CreateAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAgent'
type MockAgentRepository_CreateAgent_Call struct {
	*mock.Call
}

// CreateAgent is a helper method to define mock.On call
//   - ctx context.Context
//   - agent *agent_model.Agent
func (_e *MockAgentRepository_Expecter) CreateAgent(ctx any, agent any) *MockAgentRepository_CreateAgent_Call {
	return &MockAgentRepository_CreateAgent_Call{Call: _e.mock.On("CreateAgent", ctx, agent)}
}

func (_c *MockAgentRepository_CreateAgent_Call) Run(run func(ctx context.Context, agent *agent_model.Agent)) *MockAgentRepository_CreateAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *agent_model.Agent
		if args[1] != nil {
			arg1 = args[1].(*agent_model.Agent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgentRepository_CreateAgent_Call) Return(agent1 *agent_model.Agent, err error) *MockAgentRepository_CreateAgent_Call {
	_c.Call.Return(agent1, err)
	return _c
}

func (_c *MockAgentRepository_CreateAgent_Call) RunAndReturn(run func(ctx context.Context, agent *agent_model.Agent) (*agent_model.Agent, error)) *MockAgentRepository_CreateAgent_Call {
	_c.Call.Return(run)
	return _c
}

// GetAgentByID provides a mock function for the type MockAgentRepository
func (_mock *MockAgentRepository) GetAgentByID(ctx context.Context, id uuid.UUID) (*agent_model.Agent, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAgentByID")
	}

	var r0 *agent_model.Agent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*agent_model.Agent, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *agent_model.Agent); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agent_model.Agent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentRepository_GetAgentByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAgentByID'
type MockAgentRepository_GetAgentByID_Call struct {
	*mock.Call
}

// GetAgentByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAgentRepository_Expecter) GetAgentByID(ctx any, id any) *MockAgentRepository_GetAgentByID_Call {
	return &MockAgentRepository_GetAgentByID_Call{Call: _e.mock.On("GetAgentByID", ctx, id)}
}

func (_c *MockAgentRepository_GetAgentByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAgentRepository_GetAgentByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgentRepository_GetAgentByID_Call) Return(res *agent_model.Agent, err error) *MockAgentRepository_GetAgentByID_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *MockAgentRepository_GetAgentByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*agent_model.Agent, error)) *MockAgentRepository_GetAgentByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAgentNamesByIDs provides a mock function for the type MockAgentRepository
func (_mock *MockAgentRepository) GetAgentNamesByIDs(ctx context.Context, agentIDs []uuid.UUID) (map[uuid.UUID]string, error) {
	ret := _mock.Called(ctx, agentIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetAgentNamesByIDs")
	}

	var r0 map[uuid.UUID]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) (map[uuid.UUID]string, error)); ok {
		return returnFunc(ctx, agentIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) map[uuid.UUID]string); ok {
		r0 = returnFunc(ctx, agentIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, agentIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentRepository_GetAgentNamesByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAgentNamesByIDs'
type MockAgentRepository_GetAgentNamesByIDs_Call struct {
	*mock.Call
}

// GetAgentNamesByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - agentIDs []uuid.UUID
func (_e *MockAgentRepository_Expecter) GetAgentNamesByIDs(ctx any, agentIDs any) *MockAgentRepository_GetAgentNamesByIDs_Call {
	return &MockAgentRepository_GetAgentNamesByIDs_Call{Call: _e.mock.On("GetAgentNamesByIDs", ctx, agentIDs)}
}

func (_c *MockAgentRepository_GetAgentNamesByIDs_Call) Run(run func(ctx context.Context, agentIDs []uuid.UUID)) *MockAgentRepository_GetAgentNamesByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAgentRepository_GetAgentNamesByIDs_Call) Return(uUIDToString map[uuid.UUID]string, err error) *MockAgentRepository_GetAgentNamesByIDs_Call {
	_c.Call.Return(uUIDToString, err)
	return _c
}

func (_c *MockAgentRepository_GetAgentNamesByIDs_Call) RunAndReturn(run func(ctx context.Context, agentIDs []uuid.UUID) (map[uuid.UUID]string, error)) *MockAgentRepository_GetAgentNamesByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllAgents provides a mock function for the type MockAgentRepository
func (_mock *MockAgentRepository) GetAllAgents(ctx context.Context) ([]*agent_model.Agent, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllAgents")
	}

	var r0 []*agent_model.Agent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*agent_model.Agent, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*agent_model.Agent); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*agent_model.Agent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentRepository_GetAllAgents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllAgents'
type MockAgentRepository_GetAllAgents_Call struct {
	*mock.Call
}

// GetAllAgents is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAgentRepository_Expecter) GetAllAgents(ctx any) *MockAgentRepository_GetAllAgents_Call {
	return &MockAgentRepository_GetAllAgents_Call{Call: _e.mock.On("GetAllAgents", ctx)}
}

func (_c *MockAgentRepository_GetAllAgents_Call) Run(run func(ctx context.Context)) *MockAgentRepository_GetAllAgents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgentRepository_GetAllAgents_Call) Return(res []*agent_model.Agent, err error) *MockAgentRepository_GetAllAgents_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *MockAgentRepository_GetAllAgents_Call) RunAndReturn(run func(ctx context.Context) ([]*agent_model.Agent, error)) *MockAgentRepository_GetAllAgents_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalAgents provides a mock function for the type MockAgentRepository
func (_mock *MockAgentRepository) GetTotalAgents(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalAgents")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAgentRepository_GetTotalAgents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalAgents'
type MockAgentRepository_GetTotalAgents_Call struct {
	*mock.Call
}

// GetTotalAgents is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAgentRepository_Expecter) GetTotalAgents(ctx any) *MockAgentRepository_GetTotalAgents_Call {
	return &MockAgentRepository_GetTotalAgents_Call{Call: _e.mock.On("GetTotalAgents", ctx)}
}

func (_c *MockAgentRepository_GetTotalAgents_Call) Run(run func(ctx context.Context)) *MockAgentRepository_GetTotalAgents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAgentRepository_GetTotalAgents_Call) Return(n int, err error) *MockAgentRepository_GetTotalAgents_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAgentRepository_GetTotalAgents_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockAgentRepository_GetTotalAgents_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockAgentRepository
func (_mock *MockAgentRepository) UpdateStatus(ctx context.Context, agentID uuid.UUID, status agent_model.AgentStatus) error {
	ret := _mock.Called(ctx, agentID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, agent_model.AgentStatus) error); ok {
		r0 = returnFunc(ctx, agentID, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAgentRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockAgentRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - agentID uuid.UUID
//   - status agent_model.AgentStatus
func (_e *MockAgentRepository_Expecter) UpdateStatus(ctx any, agentID any, status any) *MockAgentRepository_UpdateStatus_Call {
	return &MockAgentRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, agentID, status)}
}

func (_c *MockAgentRepository_UpdateStatus_Call) Run(run func(ctx context.Context, agentID uuid.UUID, status agent_model.AgentStatus)) *MockAgentRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 agent_model.AgentStatus
		if args[2] != nil {
			arg2 = args[2].(agent_model.AgentStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAgentRepository_UpdateStatus_Call) Return(err error) *MockAgentRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAgentRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, agentID uuid.UUID, status agent_model.AgentStatus) error) *MockAgentRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEnrollmentKeysRepository creates a new instance of MockEnrollmentKeysRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnrollmentKeysRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnrollmentKeysRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockEnrollmentKeysRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockEnrollmentKeysRepository is an autogenerated mock type for the EnrollmentKeysRepository type
type MockEnrollmentKeysRepository struct {
	mock.Mock
}

type MockEnrollmentKeysRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnrollmentKeysRepository) EXPECT() *MockEnrollmentKeysRepository_Expecter {
	return &MockEnrollmentKeysRepository_Expecter{mock: &_m.Mock}
}

// CreateKey provides a mock function for the type MockEnrollmentKeysRepository
func (_mock *MockEnrollmentKeysRepository) CreateKey(ctx context.Context, key *agent_model.EnrollmentKey) (*agent_model.EnrollmentKey, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for CreateKey")
	}

	var r0 *agent_model.EnrollmentKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *agent_model.EnrollmentKey) (*agent_model.EnrollmentKey, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *agent_model.EnrollmentKey) *agent_model.EnrollmentKey); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agent_model.EnrollmentKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *agent_model.EnrollmentKey) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEnrollmentKeysRepository_CreateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKey'
type MockEnrollmentKeysRepository_CreateKey_Call struct {
	*mock.Call
}

// CreateKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key *agent_model.EnrollmentKey
func (_e *MockEnrollmentKeysRepository_Expecter) CreateKey(ctx any, key any) *MockEnrollmentKeysRepository_CreateKey_Call {
	return &MockEnrollmentKeysRepository_CreateKey_Call{Call: _e.mock.On("CreateKey", ctx, key)}
}

func (_c *MockEnrollmentKeysRepository_CreateKey_Call) Run(run func(ctx context.Context, key *agent_model.EnrollmentKey)) *MockEnrollmentKeysRepository_CreateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *agent_model.EnrollmentKey
		if args[1] != nil {
			arg1 = args[1].(*agent_model.EnrollmentKey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEnrollmentKeysRepository_CreateKey_Call) Return(enrollmentKey *agent_model.EnrollmentKey, err error) *MockEnrollmentKeysRepository_CreateKey_Call {
	_c.Call.Return(enrollmentKey, err)
	return _c
}

func (_c *MockEnrollmentKeysRepository_CreateKey_Call) RunAndReturn(run func(ctx context.Context, key *agent_model.EnrollmentKey) (*agent_model.EnrollmentKey, error)) *MockEnrollmentKeysRepository_CreateKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetKeyByAgentId provides a mock function for the type MockEnrollmentKeysRepository
func (_mock *MockEnrollmentKeysRepository) GetKeyByAgentId(ctx context.Context, agentID uuid.UUID) (*agent_model.EnrollmentKey, error) {
	ret := _mock.Called(ctx, agentID)

	if len(ret) == 0 {
		panic("no return value specified for GetKeyByAgentId")
	}

	var r0 *agent_model.EnrollmentKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*agent_model.EnrollmentKey, error)); ok {
		return returnFunc(ctx, agentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *agent_model.EnrollmentKey); ok {
		r0 = returnFunc(ctx, agentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agent_model.EnrollmentKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, agentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEnrollmentKeysRepository_GetKeyByAgentId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKeyByAgentId'
type MockEnrollmentKeysRepository_GetKeyByAgentId_Call struct {
	*mock.Call
}

// GetKeyByAgentId is a helper method to define mock.On call
//   - ctx context.Context
//   - agentID uuid.UUID
func (_e *MockEnrollmentKeysRepository_Expecter) GetKeyByAgentId(ctx any, agentID any) *MockEnrollmentKeysRepository_GetKeyByAgentId_Call {
	return &MockEnrollmentKeysRepository_GetKeyByAgentId_Call{Call: _e.mock.On("GetKeyByAgentId", ctx, agentID)}
}

func (_c *MockEnrollmentKeysRepository_GetKeyByAgentId_Call) Run(run func(ctx context.Context, agentID uuid.UUID)) *MockEnrollmentKeysRepository_GetKeyByAgentId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEnrollmentKeysRepository_GetKeyByAgentId_Call) Return(enrollmentKey *agent_model.EnrollmentKey, err error) *MockEnrollmentKeysRepository_GetKeyByAgentId_Call {
	_c.Call.Return(enrollmentKey, err)
	return _c
}

func (_c *MockEnrollmentKeysRepository_GetKeyByAgentId_Call) RunAndReturn(run func(ctx context.Context, agentID uuid.UUID) (*agent_model.EnrollmentKey, error)) *MockEnrollmentKeysRepository_GetKeyByAgentId_Call {
	_c.Call.Return(run)
	return _c
}

// GetKeyBySelector provides a mock function for the type MockEnrollmentKeysRepository
func (_mock *MockEnrollmentKeysRepository) GetKeyBySelector(ctx context.Context, selector string) (*agent_model.EnrollmentKey, error) {
	ret := _mock.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for GetKeyBySelector")
	}

	var r0 *agent_model.EnrollmentKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*agent_model.EnrollmentKey, error)); ok {
		return returnFunc(ctx, selector)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *agent_model.EnrollmentKey); ok {
		r0 = returnFunc(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agent_model.EnrollmentKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEnrollmentKeysRepository_GetKeyBySelector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKeyBySelector'
type MockEnrollmentKeysRepository_GetKeyBySelector_Call struct {
	*mock.Call
}

// GetKeyBySelector is a helper method to define mock.On call
//   - ctx context.Context
//   - selector string
func (_e *MockEnrollmentKeysRepository_Expecter) GetKeyBySelector(ctx any, selector any) *MockEnrollmentKeysRepository_GetKeyBySelector_Call {
	return &MockEnrollmentKeysRepository_GetKeyBySelector_Call{Call: _e.mock.On("GetKeyBySelector", ctx, selector)}
}

func (_c *MockEnrollmentKeysRepository_GetKeyBySelector_Call) Run(run func(ctx context.Context, selector string)) *MockEnrollmentKeysRepository_GetKeyBySelector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEnrollmentKeysRepository_GetKeyBySelector_Call) Return(enrollmentKey *agent_model.EnrollmentKey, err error) *MockEnrollmentKeysRepository_GetKeyBySelector_Call {
	_c.Call.Return(enrollmentKey, err)
	return _c
}

func (_c *MockEnrollmentKeysRepository_GetKeyBySelector_Call) RunAndReturn(run func(ctx context.Context, selector string) (*agent_model.EnrollmentKey, error)) *MockEnrollmentKeysRepository_GetKeyBySelector_Call {
	_c.Call.Return(run)
	return _c
}

// SetUsed provides a mock function for the type MockEnrollmentKeysRepository
func (_mock *MockEnrollmentKeysRepository) SetUsed(ctx context.Context, agentID uuid.UUID, usedAt time.Time) error {
	ret := _mock.Called(ctx, agentID, usedAt)

	if len(ret) == 0 {
		panic("no return value specified for SetUsed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = returnFunc(ctx, agentID, usedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEnrollmentKeysRepository_SetUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUsed'
type MockEnrollmentKeysRepository_SetUsed_Call struct {
	*mock.Call
}

// SetUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - agentID uuid.UUID
//   - usedAt time.Time
func (_e *MockEnrollmentKeysRepository_Expecter) SetUsed(ctx any, agentID any, usedAt any) *MockEnrollmentKeysRepository_SetUsed_Call {
	return &MockEnrollmentKeysRepository_SetUsed_Call{Call: _e.mock.On("SetUsed", ctx, agentID, usedAt)}
}

func (_c *MockEnrollmentKeysRepository_SetUsed_Call) Run(run func(ctx context.Context, agentID uuid.UUID, usedAt time.Time)) *MockEnrollmentKeysRepository_SetUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEnrollmentKeysRepository_SetUsed_Call) Return(err error) *MockEnrollmentKeysRepository_SetUsed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEnrollmentKeysRepository_SetUsed_Call) RunAndReturn(run func(ctx context.Context, agentID uuid.UUID, usedAt time.Time) error) *MockEnrollmentKeysRepository_SetUsed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSpecsRepository creates a new instance of MockSpecsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSpecsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSpecsRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSpecsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSpecsRepository is an autogenerated mock type for the SpecsRepository type
type MockSpecsRepository struct {
	mock.Mock
}

type MockSpecsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSpecsRepository) EXPECT() *MockSpecsRepository_Expecter {
	return &MockSpecsRepository_Expecter{mock: &_m.Mock}
}

// CreateOrUpdateSpecs provides a mock function for the type MockSpecsRepository
func (_mock *MockSpecsRepository) CreateOrUpdateSpecs(ctx context.Context, specs *agent_model.Specs) (*agent_model.Specs, error) {
	ret := _mock.Called(ctx, specs)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrUpdateSpecs")
	}

	var r0 *agent_model.Specs
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *agent_model.Specs) (*agent_model.Specs, error)); ok {
		return returnFunc(ctx, specs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *agent_model.Specs) *agent_model.Specs); ok {
		r0 = returnFunc(ctx, specs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agent_model.Specs)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *agent_model.Specs) error); ok {
		r1 = returnFunc(ctx, specs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSpecsRepository_CreateOrUpdateSpecs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrUpdateSpecs'
type MockSpecsRepository_CreateOrUpdateSpecs_Call struct {
	*mock.Call
}

// CreateOrUpdateSpecs is a helper method to define mock.On call
//   - ctx context.Context
//   - specs *agent_model.Specs
func (_e *MockSpecsRepository_Expecter) CreateOrUpdateSpecs(ctx any, specs any) *MockSpecsRepository_CreateOrUpdateSpecs_Call {
	return &MockSpecsRepository_CreateOrUpdateSpecs_Call{Call: _e.mock.On("CreateOrUpdateSpecs", ctx, specs)}
}

func (_c *MockSpecsRepository_CreateOrUpdateSpecs_Call) Run(run func(ctx context.Context, specs *agent_model.Specs)) *MockSpecsRepository_CreateOrUpdateSpecs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *agent_model.Specs
		if args[1] != nil {
			arg1 = args[1].(*agent_model.Specs)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSpecsRepository_CreateOrUpdateSpecs_Call) Return(specs1 *agent_model.Specs, err error) *MockSpecsRepository_CreateOrUpdateSpecs_Call {
	_c.Call.Return(specs1, err)
	return _c
}

func (_c *MockSpecsRepository_CreateOrUpdateSpecs_Call) RunAndReturn(run func(ctx context.Context, specs *agent_model.Specs) (*agent_model.Specs, error)) *MockSpecsRepository_CreateOrUpdateSpecs_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentSpecs provides a mock function for the type MockSpecsRepository
func (_mock *MockSpecsRepository) GetCurrentSpecs(ctx context.Context, agentID uuid.UUID) (*agent_model.Specs, error) {
	ret := _mock.Called(ctx, agentID)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentSpecs")
	}

	var r0 *agent_model.Specs
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*agent_model.Specs, error)); ok {
		return returnFunc(ctx, agentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *agent_model.Specs); ok {
		r0 = returnFunc(ctx, agentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*agent_model.Specs)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, agentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSpecsRepository_GetCurrentSpecs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentSpecs'
type MockSpecsRepository_GetCurrentSpecs_Call struct {
	*mock.Call
}

// GetCurrentSpecs is a helper method to define mock.On call
//   - ctx context.Context
//   - agentID uuid.UUID
func (_e *MockSpecsRepository_Expecter) GetCurrentSpecs(ctx any, agentID any) *MockSpecsRepository_GetCurrentSpecs_Call {
	return &MockSpecsRepository_GetCurrentSpecs_Call{Call: _e.mock.On("GetCurrentSpecs", ctx, agentID)}
}

func (_c *MockSpecsRepository_GetCurrentSpecs_Call) Run(run func(ctx context.Context, agentID uuid.UUID)) *MockSpecsRepository_GetCurrentSpecs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSpecsRepository_GetCurrentSpecs_Call) Return(specs *agent_model.Specs, err error) *MockSpecsRepository_GetCurrentSpecs_Call {
	_c.Call.Return(specs, err)
	return _c
}

func (_c *MockSpecsRepository_GetCurrentSpecs_Call) RunAndReturn(run func(ctx context.Context, agentID uuid.UUID) (*agent_model.Specs, error)) *MockSpecsRepository_GetCurrentSpecs_Call {
	_c.Call.Return(run)
	return _c
}

// GetSpecsTotalList provides a mock function for the type MockSpecsRepository
func (_mock *MockSpecsRepository) GetSpecsTotalList(ctx context.Context, agentIDs []uuid.UUID) (map[uuid.UUID]agent_model.SpecsTotal, error) {
	ret := _mock.Called(ctx, agentIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetSpecsTotalList")
	}

	var r0 map[uuid.UUID]agent_model.SpecsTotal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) (map[uuid.UUID]agent_model.SpecsTotal, error)); ok {
		return returnFunc(ctx, agentIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) map[uuid.UUID]agent_model.SpecsTotal); ok {
		r0 = returnFunc(ctx, agentIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID]agent_model.SpecsTotal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, agentIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSpecsRepository_GetSpecsTotalList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSpecsTotalList'
type MockSpecsRepository_GetSpecsTotalList_Call struct {
	*mock.Call
}

// GetSpecsTotalList is a helper method to define mock.On call
//   - ctx context.Context
//   - agentIDs []uuid.UUID
func (_e *MockSpecsRepository_Expecter) GetSpecsTotalList(ctx any, agentIDs any) *MockSpecsRepository_GetSpecsTotalList_Call {
	return &MockSpecsRepository_GetSpecsTotalList_Call{Call: _e.mock.On("GetSpecsTotalList", ctx, agentIDs)}
}

func (_c *MockSpecsRepository_GetSpecsTotalList_Call) Run(run func(ctx context.Context, agentIDs []uuid.UUID)) *MockSpecsRepository_GetSpecsTotalList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSpecsRepository_GetSpecsTotalList_Call) Return(uUIDToSpecsTotal map[uuid.UUID]agent_model.SpecsTotal, err error) *MockSpecsRepository_GetSpecsTotalList_Call {
	_c.Call.Return(uUIDToSpecsTotal, err)
	return _c
}

func (_c *MockSpecsRepository_GetSpecsTotalList_Call) RunAndReturn(run func(ctx context.Context, agentIDs []uuid.UUID) (map[uuid.UUID]agent_model.SpecsTotal, error)) *MockSpecsRepository_GetSpecsTotalList_Call {
	_c.Call.Return(run)
	return _c
}
